/**
 * @file bsp_board_config.h
 * @brief Centralized board device parameters.
 */
#ifndef USER_BSP_BSP_BOARD_CONFIG_H
#define USER_BSP_BSP_BOARD_CONFIG_H

#define BSP_SENSOR_I2C_ADDRESS_7BIT 0x4CU
#define BSP_SENSOR_READ_COMMAND 0xDDU
#define BSP_OLED_I2C_ADDRESS_HAL 0x78U
#define BSP_MOTOR_PWM_PERIOD 1000U
#define BSP_MOTOR_PWM_DEADZONE 30U
#define BSP_SENSOR_PERIOD_MS 3U
#define BSP_SENSOR_STALE_MS 100U
#define BSP_ENCODER_PERIOD_MS 10U
#define BSP_KEY_DEBOUNCE_MS 20U
#define BSP_ULTRASONIC_PERIOD_MS 60U

#define BSP_SERVO_ID_BASE 0U
#define BSP_SERVO_ID_TURRET 1U
#define BSP_SERVO_ID_AUX 12U
#define BSP_SERVO_INTERVAL_MS 1000U
#define BSP_SERVO_POWER 0U
#define BSP_STEPPER_ID_LEFT 1U
#define BSP_STEPPER_ID_RIGHT 2U

#endif
